
name: consulta_cep_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Assets do aplicativo
  # assets:
  #   - assets/images/

# Configuração da tela de inicialização
flutter_native_splash:
  color: "#32145C"
  image: assets/images/splash.png
  android: true
  ios: true
  fullscreen: true

  android_12:
    color: "#32145C"
    image: assets/images/splash.png

# Configuração dos ícones do aplicativo
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#32145C"
  adaptive_icon_foreground: "assets/images/app_icon.png"